openapi: 3.0.3
info:
  title: Transactions ArgentBank
  description: |-
    API pour les différentes opérations possibles sur les transactions
  version: 1.0.11

servers:
  - url: http://localhost:3002/api/v1/
tags:
  - name: Transactions
    description: Tous sur vos transactions

paths:

  /accounts:
   get:
      summary: Obtient les comptes
      description: Permet de visualiser les comptes.
      responses:
        '200':
          description: Détails des comptes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '404':
          description: Comptes non trouvé


  /accounts/{accountId}/transactions:
    parameters:
      - in: path
        name: accountId
        required: true
        schema:
          type: string
        description: L'ID unique du compte.

    get:
      summary: Récupère les transactions du mois en cours pour un compte
      description: Retourne toutes les transactions du mois en cours pour un compte donné, groupées par compte.
      parameters:
        - in: query
          name: month
          required: false
          schema:
            type: string
            example: "2024-10"
            description: Mois des transactions demandées (format YYYY-MM)
      responses:
        '200':
          description: Transactions récupérées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '404':
          description: Compte non trouvé


  

  /accounts/{accountId}/transactions/{transactionId}:
    parameters:
      - in: path
        name: accountId
        required: true
        schema:
          type: string
        description: L'ID unique du compte.
      - in: path
        name: transactionId
        required: true
        schema:
          type: string
        description: L'ID unique de la transaction.

    get:
      summary: Obtient les détails d'une transaction spécifique
      description: Permet de visualiser les détails d'une transaction.
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '404':
          description: Transaction non trouvée


    put:
      summary: Modifie une transaction
      description: Mettre à jour les informations d'une transaction spécifique.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionUpdate'
      responses:
        '200':
          description: Transaction mise à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Requête invalide
        '404':
          description: Transaction non trouvée


    delete:
      summary: Supprime des informations d'une transaction
      description: Supprime les informations ajoutées à une transaction spécifique.
      responses:
        '204':
          description: Transaction supprimée avec succès
        '404':
          description: Transaction non trouvée


components:
  schemas:
    Transaction:
      type: object
      properties:
        transactionId:
          type: string
          description: Identifiant unique de la transaction.
        accountId:
          type: string
          description: Identifiant unique du compte auquel appartient la transaction.
        date:
          type: string
          format: date
          description: Date de la transaction.
        amount:
          type: number
          format: float
          description: Montant de la transaction.
        description:
          type: string
          description: Description de la transaction.
        category:
          type: string
          description: Catégorie de la transaction.
        transactiontype:
          type: string
          description: Type de la transaction
        balance:
         type: number
         description: Balance de la transaction
          

    TransactionUpdate:
      type: object
      properties:
        description:
          type: string
          description: Mise à jour de la description de la transaction.
        category:
          type: string
          description: Mise à jour de la catégorie de la transaction.
        transactiontype:
          type: string
          description: Type de la transaction
        balance:
          type: number
          description: Balance de la transaction